TYPO3-Documentation/t3docs-search-indexer

- .ddev/docker-compose.elasticsearch.yaml
To avoid potential security risks the ElasticSearch is updated to latest
release 7.16.1 to match the version for the production environment.
This updates contains fixes for the Log4j Security Issues reported
https://www.elastic.co/guide/en/elasticsearch/reference/7.16/release-notes-7.16.1.html
> [SECURITY] Updated to latest ElasticSearch 7.16.1

- config/Elasticorn/Elasticorn.yaml
- config/Elasticorn/docsearch/IndexConfiguration.yaml
- config/Elasticorn/docsearch/Mapping.yaml
- src/Repository/ElasticRepository.php
This should allow splitting text by e.g. colon or slash, and searching parts of the word.
Fixes: https://github.com/TYPO3-Documentation/t3docs-search-indexer/issues/31
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-word-delimiter-tokenfilter.html
Add custom filter and analyzer
Add missing fields to mapping
Remove language configuration as it was conflicting with
custom analyzer config see
TYPO3GmbH/elasticorn#21
Allow searching by extension key (also by fragment
- analyze the extension key)
> Add custom word_delimiter filter

- src/Dto/Manual.php
- src/Service/DirectoryFinderService.php
The indexing script was previously validating only in the main package directory for the presence of an `objects.inv.json` file. Only directories containing this file were scanned and indexed. However, some packages like `cms-core` only have an `objects.inv` file, not `objects.inv.json`.
With this change, the existence of either `objects.inv` or `objects.inv.json` is checked to determine if a directory should be indexed.
Additionally, the list of excluded subfolders has been expanded to include `_panels_static`.
> #46 Fix indexing changelog files from cms-core extension

- config/Elasticorn/docsearch/Mapping.yaml
- src/Config/ManualType.php
- src/Dto/Manual.php
- src/Repository/ElasticRepository.php
- src/Service/ImportManualHTMLService.php
- tests/Unit/Config/ManualTypeTest.php
- tests/Unit/Dto/ManualTest.php
- tests/Unit/Service/ImportManualHTMLServiceTest.php
This commit adds new `manual_keywords` field to index. It will store most important keywords related to current manual and for now we store there only system or community extension name.
When such keyword matches any word from searched phrase, the whole query will be boosted by formula `matchedKeywords * 10`.
This computation is done through custom script score defined inside the `ElasticRepository`.
Keep in mind that we expect only full word match here, not partial.
It is important to store in the `manual_keywords` only most important keywords as they have big impact on final order.
Resolves issue: #35
> #35 Boost on extension key direct match

- composer.json
- composer.lock
To make it possible to configure the search application via `.env` files in the production environment, the necessary package `symfony/dotenv` is now required anytime.
> [BUGFIX] Require `symfony/dotenv` in production mode

- README.rst
- src/Command/IndexCleaner.php
- src/Dto/Constraints.php
- src/QueryBuilder/ElasticQueryBuilder.php
- src/Repository/ElasticRepository.php
- tests/Unit/Command/IndexCleanerTest.php
- tests/Unit/Dto/ConstraintsTest.php
- tests/Unit/QueryBuilder/ElasticQueryBuilderTest.php
This commit adds a new command `docsearch:index:delete`, which allows for the deletion of all or selected manuals from the Elasticsearch index.
It accepts the following options:
- --manual-slug: The slug of the manual to be removed from the index
- --manual-version: The version of the manual to be removed from the index
- --manual-type: The type of the manual to be removed from the index
- --manual-language: The language of the manual to be removed from the index
To execute the command, type:
`bin/console docsearch:index:delete`
To remove, for example, a specific manual version, type:
`bin/console docsearch:index:delete --manual-version=12.4`
Multiple options can be combined for more targeted deletions.
Resolves issue: #13
> #13 Add command to remove manuals from index by given constraints

- config/Elasticorn/docsearch/Mapping.yaml
- src/Dto/SearchDemand.php
- src/Helper/VersionFilter.php
- src/Repository/ElasticRepository.php
- src/Twig/AppExtension.php
- templates/search/search.html.twig
- tests/Unit/Dto/SearchDemandTest.php
- tests/Unit/Helper/VersionFilterTest.php
This commit replaces the all versions aggregation by only major versions.
There is also change for the search results list. Before labels for all versions assigned to the snippet were rendered. After the changes only the highest version in given branch will be rendered. For example, if snippet has versions `main`, `12.4`, `12.0`, `11.5`, `11.3`, `11.0`, `9.5`, only labels for `main`,`12.4`, `11.5`, `9.5` will be rendered.
Resolves issue: #14
> #14 Aggregate only major versions and render labels for highest versions

- config/services.yaml
- src/Controller/SearchController.php
- src/Dto/SearchDemand.php
- src/Twig/AppExtension.php
- templates/partial/aggregations.html.twig
- templates/partial/base/breadcrumbs.html.twig
- templates/partial/base/page_header.html.twig
- templates/partial/paginator.html.twig
- templates/search/search.html.twig
- tests/Unit/Dto/SearchDemandTest.php
This commit follows up on the changes made in the Rendering Guides repository, where a new option for searching within a single manual scope was introduced.
These changes implement the same functionality for the search results page:
- The search form has been updated to display a list of search scopes (All | Current).
- The selected scope is now passed as a filter to the Elasticsearch query to match against manual_slug.
- If a scope is selected, facets are hidden on the search results page.
- Styles have been updated to the latest version.
- Several improvements have been made to the templates.
> [TASK] Allow searching only inside single manual scope

- src/Service/DirectoryFinderService.php
- tests/Unit/Service/DirectoryFinderServiceTest.php
Since the `c/typo3/cms-core` contains only changelog manuals, and according to the documentation team only the `main` versions should be indexed, with this commit all other versions from the `typo3/cms-core` will be ignored.
Resolves #74
> [TASK] Index only main version from the typo3/cms-core package

- templates/search/search.html.twig
To prevent rendering HTML entities in manual snippet titles, we now pass them through `raw` Twig filter. The autoescaping is still active and we will have scaped value returned from the server.
Resolves #71
> [TASK] Pass snippet title through raw filter

- CHANGELOG.md
- src/Service/ImportManualHTMLService.php
- src/Service/ParseDocumentationHTMLService.php
- tests/Unit/Command/IndexCleanerTest.php
- tests/Unit/Command/SnippetImporterTest.php
- tests/Unit/Config/ManualTypeTest.php
- tests/Unit/Controller/SearchControllerTest.php
- tests/Unit/Dto/ManualTest.php
- tests/Unit/Service/ImportManualHTMLServiceTest.php
- tests/Unit/Service/ParseDocumentationHTMLServiceTest.php
With this commit, all Changelog files will be treated as a single snippet when importing their content into the search index.
The underlying logic to parse documentation file content remains unchanged:
- Files excluded by configuration or dedicated meta tags will still be excluded
- All snippets from a file will be fetched
Next, for Changelog files, the snippets from a single file are merged  into a single snippet:
- The title (headline) from the first snippet will be used as the title  for the merged snippet
- The merged content is created by concatenating the content of the  first snippet with the title and content of every subsequent snippet.
Important: After merging, the search index must be cleared and the  indexing process must be re-run.
Resolves #29
> [TASK] Index Changelog files as a single snippets

- .ddev/config.yaml
As far as I know, there is no need for MariaDB on this project. So we can remove the default DDEV db container from the local env.
> [TASK] Remove the db container on DDEV as it's not needed

- .ddev/config.yaml
- config/services.yaml
- src/Twig/AppExtension.php
- templates/layout/base.html.twig
- templates/partial/base/breadcrumbs.html.twig
- templates/partial/base/page_header.html.twig
- templates/partial/page_main/meta-menu.html.twig
- templates/partial/page_main/navigation.html.twig
- templates/search/index.html.twig
- Removed the headerlink because it is not needed here
- Updated the Assets
- Added the all documentation button
- added Report issue, How to edit Button + changed the styling of "Edit on Github" Button
- Added the Mobile Navigation
> 94 update templates

- .ddev/nginx/cors.conf
- src/Controller/SearchController.php
- src/Dto/SearchDemand.php
- src/Repository/ElasticRepository.php
Improve the suggestion API needed in https://github.com/TYPO3-Documentation/render-guides/pull/851:
- add the package slug to send the user directly to a package Index page
- search with empty query are now allowed if you have a filter - for example listing all documents from a vendor
- when scoping with both a package and a version, the slug points to the requested version :star_struck: 
On the developer side:
- I added a cors configuration in DDEV, allowing to use the API from JavaScript between the two DDEV projects
- No reindexation needed, this can be deployed like this :+1:
> [TASK] Improve suggestion endpoint to expose slugs and support vendor

- src/Dto/SearchDemand.php
- src/Repository/ElasticRepository.php
Refs: #89 
When using "search current", the current manual slug is used as a filter.
This works fine for documentation but changelog are a bit different.
The goal of this PR is to swap the "current slug" for changelog by a broader "current type" filter, which is more relevant when it come to changelog because it does not restrict by version.
> [FIX] Add special handling of Changelog scope to use "type" instead of "slug"

- CHANGELOG.md
- src/Controller/SearchController.php
- src/Dto/SearchDemand.php
- src/Repository/ElasticRepository.php
- src/Twig/AppExtension.php
- templates/partial/aggregations.html.twig
- templates/search/search.html.twig
- tests/Unit/Dto/SearchDemandTest.php
Adds "all" and "latest" as major version to be able to filter them via aggregations / facet navigation.
- Those version are always on top even if the doc_count is not high
- The "latest" is selected by default as it was the behavior introduced in #107 
- Also removed usage of `$_GET` in Twig Extension (bad practice)
> [!WARNING]  
> To see the new version filters, a full reindex is needed. Also expect strange results during the reindex as the search query from #107 are changed.
As the version tag "latest" is in the index, when a new major version comes out, a reindex of the full module must be done so that the version N-3 loss it's "latest" tag.
> [!IMPORTANT]  
> When updating `t3docs/typo3-version-handling`, run a full reindex.
---
> [TASK] Add "latest" and "all" version facet

- src/Repository/ElasticRepository.php
Refs: #111
Both LTS versions (12 and 13) were getting a boost
Only Stable (13) is getting a boost
> [TASK] Only boost the Stable version on search results

- CHANGELOG.md
- src/Repository/ElasticRepository.php
- templates/search/search.html.twig
Refs: #80
Change how searches are done:
- replace query_string by multi_match (query_string is not [recommended for production search boxes](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html))
- tune the fields boost to reduce the gap between title and content
- add a "signal" with operator "and" allowing a greater score for documents matching all the keywords*
Change how searches results are shown:
- it was configured with one 400 chars fragment, changed to two 200 chars fragments to better show matches in contents
Overhaul I feel search results are way better but it's only an opinion :yum: 
| Before | After |
|--------|--------|
| Temporary File ![image](https://github.com/user-attachments/assets/64dea4d5-2874-42ea-83f0-ee757fe377ec) | …
> [TASK] Improve search pertinency on multi-word + general scoring

- CHANGELOG.md
- README.rst
- config/Elasticorn/docsearch/Mapping.yaml
- src/Dto/Manual.php
- src/Repository/ElasticRepository.php
- src/Service/ParseDocumentationHTMLService.php
- tests/Unit/Service/Fixtures/ParseDocumentationHTMLServiceTest/ReturnsSectionsFromFile/MarkupWithSubSections.html
- tests/Unit/Service/ParseDocumentationHTMLServiceTest.php
Refs: #33
Introduce a new way to push some words in the search index.
As described in https://github.com/TYPO3-Documentation/t3docs-search-indexer/issues/33#issuecomment-1865845721 ; you can now add a `data-keywords` attribute on documentation `<section>`.
```html
<section class="section" id="typo3-admin-panel" data-keywords="administation, backend">
```
Those keywords are comma separated (whitespaces allowed, no impact).
This can be used:
- as synonym (a page talking about "admin panel" can now match "admin backend")
- as extra keywords for search
The new field is analyzed like the others so plural form, case and stemming are handled.
```yaml
keywords:
type: text
analyzer: typo3_analyzer
```
> [!IMPORTANT]  
> A full remap will be needed for this feature to be visible live
> [TASK] Index section keywords to alter search results

- templates/layout/base.html.twig
- templates/partial/base/page_header.html.twig
https://github.com/TYPO3-Documentation/render-guides/issues/928
- Change `pageHeader.html.twig` to apply changes made on https://github.com/TYPO3-Documentation/render-guides/pull/933
- Add slot to allow second search input above results
> Add slot for search input in result page
